# Generated by Django 5.1.6 on 2025-02-14 00:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_likedislike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeDislike',
            new_name='LikeDislikeComment',
        ),
    ]
