# Generated by Django 5.1.6 on 2025-02-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
